remote_theme: clzirbel/github-pages-theme
title: Investment Return Calculator
description: Calculate average rate of return on an investment
markdown: kramdown
keywords:
 - investment
 - internal rate of return
 - average rate of return
